### ISSUE TITLE
add a readme in project details please.

### ISSUE THREAD

**Issue by alph4b3th** [gotzmann/llama.go#1]
is this the llama of the goal? is the alpaca version available? how does it work and how to install/use?

**Comment by guyvdb** [comment]
Hi, I have been watching @gotzmann as he is working on this with keen interest. I do not think it is running yet. Looks like he is still working on ml - the golang re implementation of Georgi Gerganov ggml.cpp 

You can get it to run at some stages of his checkings. It will not generate any text for you yet. Here are the steps that I took. 

1) get a copy of the LlaMa weights. This includes files: 
     tokenizer_checklist.chk
     tokenizer.model
    7B/params.json
    7B/checklist.chk
    7B/consolidated.00.pth

2) run the convert.py script. Usage: convert.py <model-dir> <ftype>

ftype can be 0 (float32) or 1 (float16) - I have only got it running on float32

3) go run ./main.go

Hope this helps.

**Comment by guyvdb** [comment]
Opps - step 2 usage:  python convert.py [model-dir] [ftype]

E.g.   python convert.py ./models 0

**Comment by alph4b3th** [comment]
> Hi, I have been watching @gotzmann as he is working on this with keen interest. I do not think it is running yet. Looks like he is still working on ml - the golang re implementation of Georgi Gerganov ggml.cpp
> 
> You can get it to run at some stages of his checkings. It will not generate any text for you yet. Here are the steps that I took.
> 
> 1. get a copy of the LlaMa weights. This includes files:
>    tokenizer_checklist.chk
>    tokenizer.model
>    7B/params.json
>    7B/checklist.chk
>    7B/consolidated.00.pth
> 2. run the convert.py script. Usage: convert.py
> 
> ftype can be 0 (float32) or 1 (float16) - I have only got it running on float32
> 
> 3. go run ./main.go
> 
> Hope this helps.


I looked at the go code and from what I could see it's easy to add a cli command to add "iterative mode". But for me to do that, I need to be sure of one thing: Is go faster than llama.cpp? I don't know if you've been following the latest issues in the llama.cpp repository, but there is a significant loss in some part of the code that causes such an absurd slowdown that it makes the use of the artificial intelligence model useless! The worst thing is that the error is intermittent, it depends on your operating system, your hardware, the model you are using, the type of your question and so far no one has been able to solve it! The solution I found is to exit llama.cpp but I haven't tested go. Do you have any speed guarantees? Do you think we have this problem too?

**Comment by gotzmann** [comment]
Hey guys, thanks for the interest! The very first project that gain some traction before any announces :)

I think today is the first day when all these draft codes started working in some meaningful way, so I've started to write down some notes at README.

To start experiment with, you'll need LLaMA model files with FP16 or FP32 data converted by Python scripts from original PyTorch models from Meta. 

I'm expecting to finish the V1 version and share it with you within next 3-4 days.

**Comment by alph4b3th** [comment]
could you somehow allow multiple instances to be used with goroutines? In llama.cpp they used operating system threads and it is not possible to upload many instances of llama, in go I believe that because of the gooroutines it is possible to process several instances (of course, with them sharing the cpu's)

**Comment by gotzmann** [comment]
@BrunoIsaac27 Yeah, one of the main goals is to allow parallel inference on the same memory instance for multi-core machines. So we'll be able to use it for some production use cases handling simultaneous requests from users at the same time. Hope to release this feature within two weeks

**Comment by alph4b3th** [comment]
@gotzmann Of course! your help is huge! I really need this feature. You can count on me, maybe the two of us together can do this functionality. Need something? I'm very good at goroutines, memory management, hardware resources, and concurrency and concurrency theory. I really know how to make the most of the hardware.

**Comment by gotzmann** [comment]
@BrunoIsaac27 Sounds good! Maybe you'll have some ideas about how to implement INT4 / INT8 quantisation and matrix max optimal way to use AVX instructions? From what I know, there no INT8 multiplication with / without saturation, which complicate things...

Take a look here: https://www.officedaytime.com/simd512e/

**Comment by gotzmann** [comment]
BTW, I'm going to close this particular thread, the README is ready and will be updated according to project status.
