### ISSUE TITLE
Postman gives "Cannot POST /" error with server mode.

### ISSUE THREAD

**Issue by ffreality** [gotzmann/llama.go#19]
I started `llama-go-v1.4.0.exe` with these CLI code (I started CMD as administrator)
`llama-go-v1.4.0 --model llama-7b-fp32.bin --server --host 127.0.0.1 --port 8082 --pods 1 -- threads 4`

and it gave me this output.
[ INIT ] REST server ready on 127.0.0.1:8082
![llama-go_server_error](https://user-images.githubusercontent.com/10528447/236907128-8557a147-6fb4-425f-99f6-c8e1350d7d2c.PNG)

and I tried this json formed request
```
{
    "id": "5fb8ebd0-e0c9-4759-8f7d-35590f6c9fc3",
    "prompt": "Can you connect the internet ?"
}
```
to
```
- 127.0.0.1:8082
- http://127.0.0.1:8082
- localhost:8082
```

but it gave me an error like this. `Cannot POST /`
![image](https://user-images.githubusercontent.com/10528447/236908036-45b56128-6ced-4553-b041-ec78723c5791.png)

and `http://localhost:8082/jobs/status/5fb8ebd0-e0c9-4759-8f7d-35590f6c9fc3` couldn't find any request with that ID.

Is there any suggestion for that ?

System:
```
Intel i7 6900K 8 Core 16 Thread
64 GB DDR4 RAM
RTX 2080S
Samsung 980 NVMe
Windows Server 2022 Standart
```
I don't think my system can't handle 1 pod with 4 thread.

**Comment by ffreality** [comment]
I tried to open ports from 8080 to 8085 and but it didn't work. I am using given binaries.

**Comment by gtsteffaniak** [comment]
post to `http://localhost:port/jobs`

its not documented
